"""add_phase_2_personalization_skills_preferences

Revision ID: 16d32cd32477
Revises: 8b4a84077d28
Create Date: 2026-09-12 13:58:30.369623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d32cd32477'
down_revision: Union[str, None] = '8b4a84077d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_relevance_score', sa.Integer(), nullable=False),
    sa.Column('instant_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=10), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('max_alerts_per_day', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_preferences_id'), 'user_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_telegram_chat_id'), 'user_notification_preferences', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_telegram_user_id'), 'user_notification_preferences', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=True)
    op.create_table('user_skills',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.add_column(sa.Column('delivery_mode', sa.String(length=50), nullable=False, server_default='instant'))
        batch_op.add_column(sa.Column('relevance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('decision_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('opportunities') as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=False, server_default='medium'))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True, server_default='India'))
        batch_op.add_column(sa.Column('required_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_opportunities_priority'), ['priority'], unique=False)

    with op.batch_alter_table('user_profiles') as batch_op:
        batch_op.add_column(sa.Column('current_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=False, server_default='Asia/Kolkata'))
        batch_op.add_column(sa.Column('career_interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_opportunity_types', sa.Text(), nullable=True))

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('user_profiles') as batch_op:
        batch_op.drop_column('preferred_opportunity_types')
        batch_op.drop_column('career_interests')
        batch_op.drop_column('timezone')
        batch_op.drop_column('current_year')

    with op.batch_alter_table('opportunities') as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_priority'))
        batch_op.drop_column('tags')
        batch_op.drop_column('required_skills')
        batch_op.drop_column('country')
        batch_op.drop_column('priority')

    with op.batch_alter_table('notifications') as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('decision_reason')
        batch_op.drop_column('relevance_score')
        batch_op.drop_column('delivery_mode')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_telegram_user_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_telegram_chat_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
