"""add_source_metrics_and_opportunity_unique_constraints

Revision ID: ad8ee8a54748
Revises: ae04da361e40
Create Date: 2026-09-10 23:25:57.483143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8ee8a54748'
down_revision: Union[str, None] = 'ae04da361e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_content_hash'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_content_hash'), 'opportunities', ['content_hash'], unique=True)
    op.drop_index(op.f('ix_opportunities_slug'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_slug'), 'opportunities', ['slug'], unique=True)
    op.add_column('sources', sa.Column('last_successful_check', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sources_base_url'), 'sources', ['base_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_base_url'), table_name='sources')
    op.drop_column('sources', 'failure_count')
    op.drop_column('sources', 'last_successful_check')
    op.drop_index(op.f('ix_opportunities_slug'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_slug'), 'opportunities', ['slug'], unique=False)
    op.drop_index(op.f('ix_opportunities_content_hash'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_content_hash'), 'opportunities', ['content_hash'], unique=False)
    # ### end Alembic commands ###
