"""add_phase_1c_a_program_watch_tables

Revision ID: 87f0cc14b731
Revises: 467ad4d0d1de
Create Date: 2026-09-12 13:09:51.247407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f0cc14b731'
down_revision: Union[str, None] = '467ad4d0d1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_watches',
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_watches_canonical_name'), 'program_watches', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_program_watches_id'), 'program_watches', ['id'], unique=False)
    op.create_index(op.f('ix_program_watches_is_active'), 'program_watches', ['is_active'], unique=False)
    op.create_index(op.f('ix_program_watches_name'), 'program_watches', ['name'], unique=False)
    op.create_index(op.f('ix_program_watches_organization_id'), 'program_watches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_program_watches_priority'), 'program_watches', ['priority'], unique=False)
    op.create_table('program_watch_aliases',
    sa.Column('program_watch_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_watch_id'], ['program_watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_watch_id', 'normalized_alias', name='uq_program_watch_alias')
    )
    op.create_index(op.f('ix_program_watch_aliases_id'), 'program_watch_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_program_watch_aliases_normalized_alias'), 'program_watch_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_program_watch_aliases_program_watch_id'), 'program_watch_aliases', ['program_watch_id'], unique=False)
    op.create_table('program_watch_keywords',
    sa.Column('program_watch_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_distinctive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_watch_id'], ['program_watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_watch_id', 'normalized_keyword', name='uq_program_watch_keyword')
    )
    op.create_index(op.f('ix_program_watch_keywords_id'), 'program_watch_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_program_watch_keywords_normalized_keyword'), 'program_watch_keywords', ['normalized_keyword'], unique=False)
    op.create_index(op.f('ix_program_watch_keywords_program_watch_id'), 'program_watch_keywords', ['program_watch_id'], unique=False)
    op.create_table('program_watch_matches',
    sa.Column('program_watch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_discovery_id', sa.String(length=36), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_level', sa.String(length=50), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=False),
    sa.Column('matched_terms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_watch_id'], ['program_watches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_discovery_id'], ['raw_discoveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_watch_id', 'raw_discovery_id', name='uq_program_watch_raw_discovery_match')
    )
    op.create_index(op.f('ix_program_watch_matches_id'), 'program_watch_matches', ['id'], unique=False)
    op.create_index(op.f('ix_program_watch_matches_match_level'), 'program_watch_matches', ['match_level'], unique=False)
    op.create_index(op.f('ix_program_watch_matches_match_score'), 'program_watch_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_program_watch_matches_program_watch_id'), 'program_watch_matches', ['program_watch_id'], unique=False)
    op.create_index(op.f('ix_program_watch_matches_raw_discovery_id'), 'program_watch_matches', ['raw_discovery_id'], unique=False)
    op.create_table('program_watch_sources',
    sa.Column('program_watch_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_watch_id'], ['program_watches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_watch_sources_id'), 'program_watch_sources', ['id'], unique=False)
    op.create_index(op.f('ix_program_watch_sources_is_active'), 'program_watch_sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_program_watch_sources_program_watch_id'), 'program_watch_sources', ['program_watch_id'], unique=False)
    op.create_index(op.f('ix_program_watch_sources_source_id'), 'program_watch_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_watch_sources_source_id'), table_name='program_watch_sources')
    op.drop_index(op.f('ix_program_watch_sources_program_watch_id'), table_name='program_watch_sources')
    op.drop_index(op.f('ix_program_watch_sources_is_active'), table_name='program_watch_sources')
    op.drop_index(op.f('ix_program_watch_sources_id'), table_name='program_watch_sources')
    op.drop_table('program_watch_sources')
    op.drop_index(op.f('ix_program_watch_matches_raw_discovery_id'), table_name='program_watch_matches')
    op.drop_index(op.f('ix_program_watch_matches_program_watch_id'), table_name='program_watch_matches')
    op.drop_index(op.f('ix_program_watch_matches_match_score'), table_name='program_watch_matches')
    op.drop_index(op.f('ix_program_watch_matches_match_level'), table_name='program_watch_matches')
    op.drop_index(op.f('ix_program_watch_matches_id'), table_name='program_watch_matches')
    op.drop_table('program_watch_matches')
    op.drop_index(op.f('ix_program_watch_keywords_program_watch_id'), table_name='program_watch_keywords')
    op.drop_index(op.f('ix_program_watch_keywords_normalized_keyword'), table_name='program_watch_keywords')
    op.drop_index(op.f('ix_program_watch_keywords_id'), table_name='program_watch_keywords')
    op.drop_table('program_watch_keywords')
    op.drop_index(op.f('ix_program_watch_aliases_program_watch_id'), table_name='program_watch_aliases')
    op.drop_index(op.f('ix_program_watch_aliases_normalized_alias'), table_name='program_watch_aliases')
    op.drop_index(op.f('ix_program_watch_aliases_id'), table_name='program_watch_aliases')
    op.drop_table('program_watch_aliases')
    op.drop_index(op.f('ix_program_watches_priority'), table_name='program_watches')
    op.drop_index(op.f('ix_program_watches_organization_id'), table_name='program_watches')
    op.drop_index(op.f('ix_program_watches_name'), table_name='program_watches')
    op.drop_index(op.f('ix_program_watches_is_active'), table_name='program_watches')
    op.drop_index(op.f('ix_program_watches_id'), table_name='program_watches')
    op.drop_index(op.f('ix_program_watches_canonical_name'), table_name='program_watches')
    op.drop_table('program_watches')
    # ### end Alembic commands ###
