"""add_phase_3_cross_source_verification_and_consensus

Revision ID: 3f1c561f8361
Revises: 16d32cd32477
Create Date: 2026-09-12 14:51:36.287562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1c561f8361'
down_revision: Union[str, None] = '16d32cd32477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_sources',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('raw_discovery_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('is_official_source', sa.Boolean(), nullable=False),
    sa.Column('contributed_fields', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_discovery_id'], ['raw_discoveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'canonical_url', name='uq_opportunity_source_canonical_url')
    )
    op.create_index(op.f('ix_opportunity_sources_canonical_url'), 'opportunity_sources', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_opportunity_sources_id'), 'opportunity_sources', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_sources_opportunity_id'), 'opportunity_sources', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_sources_raw_discovery_id'), 'opportunity_sources', ['raw_discovery_id'], unique=False)
    op.create_index(op.f('ix_opportunity_sources_source_id'), 'opportunity_sources', ['source_id'], unique=False)
    op.create_table('semantic_match_candidates',
    sa.Column('opportunity_a_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_b_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.String(length=512), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_a_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_b_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_a_id', 'opportunity_b_id', name='uq_candidate_pair')
    )
    op.create_index(op.f('ix_semantic_match_candidates_id'), 'semantic_match_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_match_candidates_opportunity_a_id'), 'semantic_match_candidates', ['opportunity_a_id'], unique=False)
    op.create_index(op.f('ix_semantic_match_candidates_opportunity_b_id'), 'semantic_match_candidates', ['opportunity_b_id'], unique=False)
    op.create_index(op.f('ix_semantic_match_candidates_status'), 'semantic_match_candidates', ['status'], unique=False)
    op.create_table('verification_conflicts',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('conflicting_values', sa.Text(), nullable=True),
    sa.Column('source_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_conflicts_field_name'), 'verification_conflicts', ['field_name'], unique=False)
    op.create_index(op.f('ix_verification_conflicts_id'), 'verification_conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_verification_conflicts_opportunity_id'), 'verification_conflicts', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_verification_conflicts_status'), 'verification_conflicts', ['status'], unique=False)
    op.create_table('verified_fields',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('official_confirmation', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'field_name', name='uq_verified_field_opp_name')
    )
    op.create_index(op.f('ix_verified_fields_field_name'), 'verified_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_verified_fields_id'), 'verified_fields', ['id'], unique=False)
    op.create_index(op.f('ix_verified_fields_opportunity_id'), 'verified_fields', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_verified_fields_verification_status'), 'verified_fields', ['verification_status'], unique=False)
    op.create_table('verification_reviews',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('conflict_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolution_action', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['semantic_match_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conflict_id'], ['verification_conflicts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reviews_entity_id'), 'verification_reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_verification_reviews_entity_type'), 'verification_reviews', ['entity_type'], unique=False)
    op.create_index(op.f('ix_verification_reviews_id'), 'verification_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_verification_reviews_priority'), 'verification_reviews', ['priority'], unique=False)
    op.create_index(op.f('ix_verification_reviews_status'), 'verification_reviews', ['status'], unique=False)
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_confidence', sa.Float(), nullable=False, server_default='0.50'))
        batch_op.add_column(sa.Column('source_count', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('official_source_present', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'last_verified_at')
    op.drop_column('opportunities', 'official_source_present')
    op.drop_column('opportunities', 'source_count')
    op.drop_column('opportunities', 'verification_confidence')
    op.drop_index(op.f('ix_verification_reviews_status'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_priority'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_id'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_entity_type'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_entity_id'), table_name='verification_reviews')
    op.drop_table('verification_reviews')
    op.drop_index(op.f('ix_verified_fields_verification_status'), table_name='verified_fields')
    op.drop_index(op.f('ix_verified_fields_opportunity_id'), table_name='verified_fields')
    op.drop_index(op.f('ix_verified_fields_id'), table_name='verified_fields')
    op.drop_index(op.f('ix_verified_fields_field_name'), table_name='verified_fields')
    op.drop_table('verified_fields')
    op.drop_index(op.f('ix_verification_conflicts_status'), table_name='verification_conflicts')
    op.drop_index(op.f('ix_verification_conflicts_opportunity_id'), table_name='verification_conflicts')
    op.drop_index(op.f('ix_verification_conflicts_id'), table_name='verification_conflicts')
    op.drop_index(op.f('ix_verification_conflicts_field_name'), table_name='verification_conflicts')
    op.drop_table('verification_conflicts')
    op.drop_index(op.f('ix_semantic_match_candidates_status'), table_name='semantic_match_candidates')
    op.drop_index(op.f('ix_semantic_match_candidates_opportunity_b_id'), table_name='semantic_match_candidates')
    op.drop_index(op.f('ix_semantic_match_candidates_opportunity_a_id'), table_name='semantic_match_candidates')
    op.drop_index(op.f('ix_semantic_match_candidates_id'), table_name='semantic_match_candidates')
    op.drop_table('semantic_match_candidates')
    op.drop_index(op.f('ix_opportunity_sources_source_id'), table_name='opportunity_sources')
    op.drop_index(op.f('ix_opportunity_sources_raw_discovery_id'), table_name='opportunity_sources')
    op.drop_index(op.f('ix_opportunity_sources_opportunity_id'), table_name='opportunity_sources')
    op.drop_index(op.f('ix_opportunity_sources_id'), table_name='opportunity_sources')
    op.drop_index(op.f('ix_opportunity_sources_canonical_url'), table_name='opportunity_sources')
    op.drop_table('opportunity_sources')
    # ### end Alembic commands ###
