"""add_phase_1c_source_snapshots_organization_aliases_and_health

Revision ID: 8b4a84077d28
Revises: 87f0cc14b731
Create Date: 2026-09-12 13:30:18.232835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4a84077d28'
down_revision: Union[str, None] = '87f0cc14b731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_aliases',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'alias', name='uq_organization_alias')
    )
    op.create_index(op.f('ix_organization_aliases_id'), 'organization_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_organization_aliases_normalized_alias'), 'organization_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_organization_aliases_organization_id'), 'organization_aliases', ['organization_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_id'), 'source_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_snapshot_hash'), 'source_snapshots', ['snapshot_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('average_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='healthy'))
        batch_op.add_column(sa.Column('polling_policy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority_level', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_sources_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_column('sources', 'priority_level')
    op.drop_column('sources', 'polling_policy')
    op.drop_column('sources', 'status')
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'average_response_time')
    op.drop_column('sources', 'consecutive_failures')
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_snapshot_hash'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_organization_aliases_organization_id'), table_name='organization_aliases')
    op.drop_index(op.f('ix_organization_aliases_normalized_alias'), table_name='organization_aliases')
    op.drop_index(op.f('ix_organization_aliases_id'), table_name='organization_aliases')
    op.drop_table('organization_aliases')
    # ### end Alembic commands ###
