"""add_phase_1b_lifecycle_and_alias_fields

Revision ID: 467ad4d0d1de
Revises: 007ae98cf30c
Create Date: 2026-09-10 23:55:03.875708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ad4d0d1de'
down_revision: Union[str, None] = '007ae98cf30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_aliases',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_aliases_alias'), 'opportunity_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_opportunity_aliases_id'), 'opportunity_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_aliases_opportunity_id'), 'opportunity_aliases', ['opportunity_id'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_name', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_state', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_opportunities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_current_state'), ['current_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_year'), ['year'], unique=False)

    with op.batch_alter_table('opportunity_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_discovery_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=1024), nullable=True))
        batch_op.create_index(batch_op.f('ix_opportunity_events_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_events_source_discovery_id'), ['source_discovery_id'], unique=False)
        batch_op.create_foreign_key('fk_opp_events_source_disc', 'raw_discoveries', ['source_discovery_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raw_discoveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_classification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('matched_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_event_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_raw_discoveries_content_classification'), ['content_classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_discoveries_created_event_id'), ['created_event_id'], unique=False)
        batch_op.create_foreign_key('fk_raw_disc_created_event', 'opportunity_events', ['created_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_discoveries', type_='foreignkey')
    op.drop_index(op.f('ix_raw_discoveries_created_event_id'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_content_classification'), table_name='raw_discoveries')
    op.drop_column('raw_discoveries', 'created_event_id')
    op.drop_column('raw_discoveries', 'matched_by')
    op.drop_column('raw_discoveries', 'content_classification')
    op.drop_constraint(None, 'opportunity_events', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_events_source_discovery_id'), table_name='opportunity_events')
    op.drop_index(op.f('ix_opportunity_events_content_hash'), table_name='opportunity_events')
    op.drop_column('opportunity_events', 'source_url')
    op.drop_column('opportunity_events', 'content_hash')
    op.drop_column('opportunity_events', 'source_discovery_id')
    op.drop_index(op.f('ix_opportunities_year'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_current_state'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_canonical_name'), table_name='opportunities')
    op.drop_column('opportunities', 'current_state')
    op.drop_column('opportunities', 'year')
    op.drop_column('opportunities', 'season')
    op.drop_column('opportunities', 'canonical_name')
    op.drop_index(op.f('ix_opportunity_aliases_opportunity_id'), table_name='opportunity_aliases')
    op.drop_index(op.f('ix_opportunity_aliases_id'), table_name='opportunity_aliases')
    op.drop_index(op.f('ix_opportunity_aliases_alias'), table_name='opportunity_aliases')
    op.drop_table('opportunity_aliases')
    # ### end Alembic commands ###
