"""add_phase_4_user_opportunity_interactions

Revision ID: 796ad5bd0e2b
Revises: 3f1c561f8361
Create Date: 2026-09-12 15:20:09.815611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796ad5bd0e2b'
down_revision: Union[str, None] = '3f1c561f8361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_opportunity_interactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_followed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity_interaction')
    )
    op.create_index(op.f('ix_user_opportunity_interactions_id'), 'user_opportunity_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_opportunity_interactions_is_followed'), 'user_opportunity_interactions', ['is_followed'], unique=False)
    op.create_index(op.f('ix_user_opportunity_interactions_is_saved'), 'user_opportunity_interactions', ['is_saved'], unique=False)
    op.create_index(op.f('ix_user_opportunity_interactions_opportunity_id'), 'user_opportunity_interactions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_user_opportunity_interactions_user_id'), 'user_opportunity_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_opportunity_interactions_user_id'), table_name='user_opportunity_interactions')
    op.drop_index(op.f('ix_user_opportunity_interactions_opportunity_id'), table_name='user_opportunity_interactions')
    op.drop_index(op.f('ix_user_opportunity_interactions_is_saved'), table_name='user_opportunity_interactions')
    op.drop_index(op.f('ix_user_opportunity_interactions_is_followed'), table_name='user_opportunity_interactions')
    op.drop_index(op.f('ix_user_opportunity_interactions_id'), table_name='user_opportunity_interactions')
    op.drop_table('user_opportunity_interactions')
    # ### end Alembic commands ###
