"""add_raw_discoveries_table

Revision ID: 007ae98cf30c
Revises: ad8ee8a54748
Create Date: 2026-09-10 23:37:52.431658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007ae98cf30c'
down_revision: Union[str, None] = 'ad8ee8a54748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_discoveries',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('raw_title', sa.String(length=512), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_reason', sa.Text(), nullable=True),
    sa.Column('connector_metadata', sa.JSON(), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_discoveries_canonical_url'), 'raw_discoveries', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_content_hash'), 'raw_discoveries', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_external_id'), 'raw_discoveries', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_id'), 'raw_discoveries', ['id'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_opportunity_id'), 'raw_discoveries', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_source_id'), 'raw_discoveries', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_discoveries_status'), 'raw_discoveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_discoveries_status'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_source_id'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_opportunity_id'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_id'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_external_id'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_content_hash'), table_name='raw_discoveries')
    op.drop_index(op.f('ix_raw_discoveries_canonical_url'), table_name='raw_discoveries')
    op.drop_table('raw_discoveries')
    # ### end Alembic commands ###
